name: CD
on: [workflow_dispatch]
jobs:
  hello2:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 1505
        script: |
          cd ~/www/AVBback
          pwd
          git pull origin main
          npm install
          npm run build
          pm2 start pm2.config.js